-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema COVID_DATA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema COVID_DATA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `COVID_DATA` DEFAULT CHARACTER SET = latin1 ;
USE `COVID_DATA` ;

-- -----------------------------------------------------
-- Table `COVID_DATA`.`Collected_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COVID_DATA`.`Collected_Data` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `ZIP_CODE` CHAR(5) NOT NULL DEFAULT 5,
  `DATE_OF_BIRTH` DATE NOT NULL,
  `HOUSEHOLD_SIZE` INT(2) NOT NULL,
  `DIFFICULTY_BREATHING` TINYINT NULL,
  `BLUE_LIPS` TINYINT NULL,
  `CHEST_PAIN` TINYINT NULL,
  `DIZZINESS` TINYINT NULL,
  `CONFUSION` TINYINT NULL,
  `SLURRED_SPEECH` TINYINT NULL,
  `SEIZURES` TINYINT NULL,
  `COVID_DIAGNOSIS` TINYINT NULL,
  `POSITIVE_TEST` TINYINT NULL,
  `TOLD_TO_QUARANTINE` TINYINT NULL,
  `PROXIMITY_TO_COVID` TINYINT NULL,
  `COUGHED_ON` TINYINT NULL,
  `LIVE_WITH_COVID` TINYINT NULL,
  `FEVER_CHILLS` TINYINT NULL,
  `COUGH` TINYINT NULL,
  `SHORTNESS_OF_BREATH` TINYINT NULL,
  `FATIGUE` TINYINT NULL,
  `BODY_ACHES` TINYINT NULL,
  `HEADACHES` TINYINT NULL,
  `LOSS_OF_TASTE_SMELL` TINYINT NULL,
  `SORE_THROAT` TINYINT NULL,
  `CONGESTION` TINYINT NULL,
  `NAUSEA_VOMITING` TINYINT NULL,
  `LUNG_DISEASE` TINYINT NULL,
  `HEART_CONDITIONS` TINYINT NULL,
  `WEAKENED_IMMUNE_SYSTEM` TINYINT NULL,
  `OBESITY` TINYINT NULL,
  `SMOKE_CIGARETTES` TINYINT NULL,
  `DIABETES` TINYINT NULL,
  `HIGH_BLOOD_PRESSURE` TINYINT NULL,
  `BLOOD_DISORDER` TINYINT NULL,
  `NEUROLOGICAL_DISEASE` TINYINT NULL,
  `CANCER` TINYINT NULL,
  `FEELING_TODAY` DECIMAL(3,1) NULL,
  `CALCULATED_SEVERITY` DECIMAL(4,3) NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
